### ISSUE TITLE
Upgrade to 2.9.0 causes Android build failure: COMPILETODALVIK PARSE error

### ISSUE THREAD

**Issue by cncb-gh** [martijn00/ExoPlayerXamarin#74]
### Steps to reproduce :scroll:

1. Upgrade via NuGet to 2.9.0

2. Rebuild Android project

### Expected behavior :thinking:
Successful build

### Actual behavior :bug:
This causes a build failure in the Android project with several of these error lines in the output:
`2>COMPILETODALVIK : PARSE error : `

Note there are no error details displayed.  If I return to the previous version I was using (2.8.5), it builds successfully.

### Configuration :wrench:

**Version:** 2.9.0

**Platform:** 
- [ ] :iphone: iOS
- [x] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
This is a problem on the Xamarin side. Since Exoplayer 2.9.0 uses Java 8 it can't compile everything correctly. Microsoft will probably fix this in Visual Studio v15.10

A possible workaround could be to add `<AndroidEnableDesugar>true</AndroidEnableDesugar>` to your csproj file.
This is related to https://github.com/xamarin/java.interop/issues/25
And https://github.com/xamarin/xamarin-android/issues/2040

**Comment by cncb-gh** [comment]
Thanks for the reply.  Unfortunately, I get a class not defined error with the "desugaring" enabled: 

`java.lang.NoClassDefFoundError :  com/google/android/exoplayer2/source/BaseMediaSource`

I will wait Microsoft to hopefully fix this soon.

**Comment by ddobrev** [comment]
I get almost identical behaviour, the only difference is that before `<AndroidEnableDesugar>true</AndroidEnableDesugar>` I get "Uncaught translation error : com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26)" instead.
I've commented on the related Xamarin issues, I hope they can fix it soon.

**Comment by ianthetechie** [comment]
I'm assuming that v15.0 is a Windows version reference? The latest VS for Mac Community (v7.6.10b27) is broken as well.

**Comment by martijn00** [comment]
Possible fix is here: https://twitter.com/_JonDouglas/status/1060691432401321984

**Comment by martijn00** [comment]
It seems to work with that fix! I've updated 2.9.1 to support this. Only problem left is that Java 1.8 features are not taken in account in the bindings. So some methods are missing.

**Comment by ianthetechie** [comment]
I assume 2.9.1 hasn't been released yet?

I just tried upgrading to 2.9.0 again since the latest VS for Mac uses OpenJDK 8. It appears the issue still persists even after the upgrade so I'm not convinced that's the only issue.

If it makes any difference, the minimum SDK version I currently support is API 21, and raising it isn't likely an option just yet. I don't expect it is for most projects either.

`COMPILETODALVIK: Error: com.android.dx.cf.code.SimException: invalid opcode ba (invokedynamic requires --min-sdk-version >= 26) (Project.Droid) Uncaught translation`

**Comment by MilkBiscuit** [comment]
> Thanks for the reply. Unfortunately, I get a class not defined error with the "desugaring" enabled:
> 
> `java.lang.NoClassDefFoundError : com/google/android/exoplayer2/source/BaseMediaSource`
> 
> I will wait for Microsoft to hopefully fix this soon.

Same issue... so disappointing.
I recommend reverting to version 2.8.8

**Comment by ianthetechie** [comment]
Ping. Any way we could get an update on NuGet to fix this? I really don't understand why it's normal for packages to remain broken for months on end in the Xamarin world (this project is far from the only offender; Microsoft packages are even worse; I'm still multiple Xamarin.Forms versions behind because subsequent updates have bugs, won't compile, etc.).

**Comment by martijn00** [comment]
2.9.4 is committed and works in VS2019 preview2. We have to wait for that to release a stable new version.

**Comment by ianthetechie** [comment]
Awesome; thanks. Out of curiosity, is there an equivalent Mac preview release?

**Comment by Daddoon** [comment]
Seems to be fixed on my side on Visual Studio 2019 Preview 2 (as i just encountered the bug). I had to add AndroidDesugar true, then everything worked on my side.

**Comment by thomashagstrom** [comment]
How is this closed? Has no label/milestone since 9.4 isn't released

**Comment by martijn00** [comment]
@thomashagstrom because there is no need for a new release to make this work. You just need to use VS2019

**Comment by thomashagstrom** [comment]
Doesn't help mac users I suppose? Rider / VS Mac gives the same error.
Even built your latest develop an hour ago and referenced those DLLs. Same issue

**Comment by martijn00** [comment]
VS2019 for Mac might work but i have no idea, try to ask Microsoft to fix this.

**Comment by cncb-gh** [comment]
I updated to the just-released VS 2019 and v2.9.0.  It compiles successfully after adding AndroidEnableDesugar but I get the following exception at runtime when setting PlayWhenReady to true:

_Java.Lang.AbstractMethodError: abstract method "void com.google.android.exoplayer2.Player$EventListener.onPlayerStateChanged(boolean, int)"_

This is discussed in  https://github.com/martijn00/ExoPlayerXamarin/issues/79#issuecomment-476568068
Is there any way around this?

**Comment by Daddoon** [comment]
Do you have the same error if your replace **<AndroidEnableDesugar>true</AndroidEnableDesugar>** to **<AndroidDexTool>d8</AndroidDexTool>** instead ?

**Comment by cncb-gh** [comment]
`<AndroidDexTool>d8</AndroidDexTool>` seems to fix the exception.  Thanks!

**Comment by cncb-gh** [comment]
No exception, but unfortunately the IPlayerEventListener methods no longer seem to be called.

**Comment by Daddoon** [comment]
Are you on VS2019 RC or VS2019 Preview ?

**Comment by cncb-gh** [comment]
The official release version from today (16.0.0 Community).

**Comment by ianthetechie** [comment]
Ditto the above. Current dev tools info:

```
=== Visual Studio Community 2019 for Mac ===

Version 8.0.1 (build 1)
Installation UUID: 588f3763-d580-45de-b809-10d8518368e1
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 5.6.0.2 (d16-0 / 040682909)

	Package version: 518010003

=== Mono Framework MDK ===

Runtime:
	Mono 5.18.1.3 (2018-08/fdb26b0a445) (64-bit)
	Package version: 518010003

=== NuGet ===

Version: 4.8.2.5835

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.2.0
	2.1.2
	2.1.1
	2.0.5
SDK: /usr/local/share/dotnet/sdk/2.2.101/Sdks
SDK Versions:
	2.2.101
	2.1.302
	2.1.301
	2.1.4
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.18.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.4
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Updater ===

Version: 11

=== Apple Developer Tools ===

Xcode 10.2 (14490.120)
Build 10E125

=== Xamarin.Mac ===

Version: 5.6.0.25 (Visual Studio Community)
Hash: 50f75273
Branch: d16-0
Build date: 2019-03-05 11:50:33-0800

=== Xamarin.iOS ===

Version: 12.6.0.25 (Visual Studio Community)
Hash: 50f75273
Branch: d16-0
Build date: 2019-03-05 11:50:33-0800

=== Xamarin.Android ===

Version: 9.2.0.5 (Visual Studio Community)
Android SDK: /Users/ianthetechie/Library/Android/sdk
	Supported Android versions:
		5.1 (API level 22)
		6.0 (API level 23)
		7.1 (API level 25)
		8.0 (API level 26)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

Build Information: 
Mono: mono/mono/2018-08-rc@5ad371dab1b
Java.Interop: xamarin/java.interop/d16-0@c987483
LibZipSharp: grendello/LibZipSharp/master@44de300
LibZip: nih-at/libzip/rel-1-5-1@b95cf3f
MXE: xamarin/mxe/xamarin@b9cbb535
ProGuard: xamarin/proguard/master@905836d
SQLite: xamarin/sqlite/3.26.0@325e91a
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-0@0a7edd6

=== Microsoft Mobile OpenJDK ===

Java SDK: /Users/ianthetechie/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_8.0.25
1.8.0-25
Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Android Device Manager ===

Version: 1.2.0.14
Hash: 86df26f
Branch: remotes/origin/d16-0
Build date: 2019-03-27 18:41:02 UTC

=== Xamarin Designer ===

Version: 4.17.4.414
Hash: 55b8d07ef
Branch: remotes/origin/d16-0
Build date: 2019-03-22 21:44:12 UTC

=== Xamarin Inspector ===

Version: 1.4.3
Hash: db27525
Branch: 1.4-release
Build date: Mon, 09 Jul 2018 21:20:18 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 800010001
Git revision: 1a426f4ef97c415b9f3cbff9e548c7db5aee09cb
Build date: 2019-04-03 18:08:51+00
Build branch: master
Xamarin extensions: 6b0f7a364694e71268aead3d501c3c35485865b1

=== Operating System ===

Mac OS X 10.14.4
Darwin 18.5.0 Darwin Kernel Version 18.5.0
    Mon Mar 11 20:40:32 PDT 2019
    root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64
```
